networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-traefik-network
#    external: true

services:
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}.traefik.main
    image: traefik:3.6.7
    hostname: ${COMPOSE_PROJECT_NAME}.hostname
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        mode: host
        protocol: tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.ziferrot.com`)
      - traefik.http.routers.traefik.entryPoints=https
      - traefik.http.routers.traefik.middlewares=authentik
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.services.traefik.loadbalancer.server.port=8443
#      - traefik.http.routers.traefik.service=traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/configs:/configs:ro
      - ./docker/traefik/certs:/certificates
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.file.directory=/configs/
      - --providers.file.watch=true
      - --global.sendAnonymousUsage=true
      - --global.checkNewVersion=false
      - --serverstransport.insecureskipverify=true
      - --providers.docker.network=${COMPOSE_PROJECT_NAME}-traefik-network
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certResolver=le
      - --certificatesresolvers.le.acme.email=admin@ziferrot.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    environment:
      TZ: ${TZ}
    networks:
      - default
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
